### ISSUE TITLE
Deployment tasks for GEOR-002

### ISSUE THREAD

**Issue by benlk** [INN/umbrella-ghn#15]
- [x] install Autoptimize and configure as described in https://github.com/INN/umbrella-ghn/issues/3
- [x] uninstall the WP Minify plugin as described in https://github.com/INN/umbrella-ghn/issues/3
- [x] replace images as described in https://github.com/INN/umbrella-ghn/issues/4
- [x] install image optimization plugin described in https://github.com/INN/umbrella-ghn/issues/4

**Comment by benlk** [comment]
:deployed: and configured.

As part of #4, the "Banner" blocks in the right-hand sidebar list of sponsors have been replaced with plain "image" blocks.
